[project]
name = "deception-bench"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "inspect-ai>=0.3.201",
    "jupyter>=1.1.1",
    "openai>=2.30.0",
    "pandas>=3.0.1",
]

[dependency-groups]
dev = [
    "pyright>=1.1.408",
]

[tool.setuptools.packages.find]
include = ["lib*"]
